routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => ['install']], function () {	

	Auth::routes();
	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

	Route::group(['middleware' => ['auth']], function () {
		
		Route::get('show_online_operator', 'DashboardController@show_online_operator');
		Route::get('dashboard', 'DashboardController@index');
		Route::get('widget_preview', 'DashboardController@widget_preview');
		Route::get('widget_code', 'DashboardController@widget_code');
        
		
		//User Controller
		Route::post('users/update_user_activity', 'UserController@update_user_activity');
		Route::resource('users','UserController');
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		
		Route::resource('departments','DepartmentController');
		Route::resource('canned_messages','CannedMessageController');
		
		//Message Controller
		Route::get('message/chat/{chat_request_id?}', 'MessageController@chat');
		Route::post('message/upload_file', 'MessageController@upload_file');
		Route::post('message/send_message', 'MessageController@send_message');
		Route::get('message/end_chat/{chat_request_id}', 'MessageController@end_chat');
		Route::get('message/get_messages/{chat_request_id}/{last_id?}', 'MessageController@get_messages');
		Route::get('message/get_chat_history_data', 'MessageController@get_chat_history_data');
		Route::get('message/chat_history/{id?}', 'MessageController@chat_history');
		Route::get('message/remove_history/{id}', 'MessageController@remove_history');	
		
		//Transfer Chat Window
		Route::get('chat/transfer_window', 'MessageController@chat_transfer_window');
		Route::get('chat/transfer_chat/{chat_request_id}/{operator_id}/{guest_id}', 'MessageController@transfer_chat');
			
		//Blacklist Controller
		Route::resource('blacklists','BlacklistController');
		
		//Offline Message
		Route::resource('offline_messages','OfflineMessageController');
		
		//Language Controller
		Route::resource('languages','LanguageController');	
		
		//Utility Controller
		Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
		Route::match(['get', 'post'],'administration/widget_settings/{store?}', 'UtilityController@widget_settings')->name('widget_settings.update');
		Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
		Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');
		Route::get('administration/toggle_offline_mode', 'UtilityController@toggle_offline_mode')->name('utility.toggle_offline_mode');
		
	});
	
});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

//Public Route
Route::get('chat_widget.js', 'GuestController@show_chat_widget');
Route::get('widget_content', 'GuestController@widget_content');
Route::post('guest/store_guest_user', 'GuestController@store_guest_user');
Route::post('guest/update_user_activity', 'GuestController@update_user_activity');
Route::post('guest/upload_file', 'GuestController@upload_file');
Route::post('guest/send_message', 'GuestController@send_message');
Route::post('guest/send_offline_message', 'GuestController@send_offline_message');
Route::get('guest/get_messages/{last_id?}', 'GuestController@get_messages');
Route::get('guest/end_chat', 'GuestController@end_chat');

app/CannedMessage.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class CannedMessage extends Model
{
    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'canned_messages';
}

app/Http/Controllers/CannedMessageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\CannedMessage;
use Validator;
use Illuminate\Validation\Rule;

class CannedMessageController extends Controller
{
	
	public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cannedmessages = CannedMessage::all()->sortByDesc("id");
        return view('backend.canned_message.list',compact('cannedmessages'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
		if( ! $request->ajax()){
		   return view('backend.canned_message.create');
		}else{
           return view('backend.canned_message.modal.create');
		}
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	
		$validator = Validator::make($request->all(), [
			'name' => 'required|max:191',
			'message' => 'required'
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect('canned_messages/create')
							->withErrors($validator)
							->withInput();
			}			
		}
			
	    
		
        $cannedmessage= new CannedMessage();
	    $cannedmessage->name = $request->input('name');
		$cannedmessage->message = $request->input('message');
	
        $cannedmessage->save();
        
		if(! $request->ajax()){
           return redirect('canned_messages/create')->with('success', _lang('Information has been added sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'store','message'=>_lang('Information has been added sucessfully'),'data'=>$cannedmessage]);
		}
        
   }
	

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $cannedmessage = CannedMessage::find($id);
		if(! $request->ajax()){
		    return view('backend.canned_message.view',compact('cannedmessage','id'));
		}else{
			return view('backend.canned_message.modal.view',compact('cannedmessage','id'));
		} 
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $cannedmessage = CannedMessage::find($id);
		if(! $request->ajax()){
		   return view('backend.canned_message.edit',compact('cannedmessage','id'));
		}else{
           return view('backend.canned_message.modal.edit',compact('cannedmessage','id'));
		}  
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$validator = Validator::make($request->all(), [
			'name' => 'required|max:191',
			'message' => 'required'
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('canned_messages.edit', $id)
							->withErrors($validator)
							->withInput();
			}			
		}
	
        	
		
        $cannedmessage = CannedMessage::find($id);
		$cannedmessage->name = $request->input('name');
		$cannedmessage->message = $request->input('message');
	
        $cannedmessage->save();
		
		if(! $request->ajax()){
           return redirect('canned_messages')->with('success', _lang('Information has been updated sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>_lang('Information has been updated sucessfully'),'data'=>$cannedmessage]);
		}
	    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cannedmessage = CannedMessage::find($id);
        $cannedmessage->delete();
        return redirect('canned_messages')->with('success',_lang('Information has been deleted sucessfully'));
    }
}

resources/views/backend/canned_message/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('Add Canned Message') }}</div>

	<div class="panel-body">
	  <div class="col-md-6">
		  <form method="post" class="validate" autocomplete="off" action="{{url('canned_messages')}}" enctype="multipart/form-data">
			{{ csrf_field() }}
			
			<div class="col-md-12">
			  <div class="form-group">
				<label class="control-label">{{ _lang('Name') }}</label>						
				<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
			  </div>
			</div>

			<div class="col-md-12">
			  <div class="form-group">
				<label class="control-label">{{ _lang('Message') }}</label>						
				<textarea class="form-control" name="message" required>{{ old('message') }}</textarea>
			  </div>
			</div>

					
			<div class="form-group">
			  <div class="col-md-12">
				<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
				<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
			  </div>
			</div>
		  </form>
	  </div>
	</div>
  </div>
 </div>
</div>
@endsection

resources/views/backend/canned_message/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">{{ _lang('Update Canned Message') }}</div>

			<div class="panel-body">
			  <div class="col-md-6">
				<form method="post" class="validate" autocomplete="off" action="{{action('CannedMessageController@update', $id)}}" enctype="multipart/form-data">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				
					
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Name') }}</label>						
						<input type="text" class="form-control" name="name" value="{{ $cannedmessage->name }}" required>
					 </div>
					</div>

					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Message') }}</label>						
						<textarea class="form-control" name="message" required>{{ $cannedmessage->message }}</textarea>
					 </div>
					</div>

					
					<div class="form-group">
					  <div class="col-md-12">
						<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
					  </div>
					</div>
				</form>
			  </div>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/canned_message/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ _lang('List Canned Message') }}</span>
			<a class="btn btn-primary btn-sm pull-right ajax-modal" data-title="{{ _lang('Add Canned Message') }}" href="{{route('canned_messages.create')}}">{{ _lang('Add New') }}</a>
			</div>

			<div class="panel-body">
			 @if (\Session::has('success'))
			  <div class="alert alert-success">
				<p>{{ \Session::get('success') }}</p>
			  </div>
			  <br />
			 @endif
			<table class="table table-bordered data-table">
			<thead>
			  <tr>
				<th>{{ _lang('Name') }}</th>
				<th>{{ _lang('Message') }}</th>
				<th style="width:250px">{{ _lang('Action') }}</th>
			  </tr>
			</thead>
			<tbody>
			  
			  @foreach($cannedmessages as $cannedmessage)
			  <tr id="row_{{ $cannedmessage->id }}">
				<td class='name'>{{ $cannedmessage->name }}</td>
				<td class='message'>{{ $cannedmessage->message }}</td>
				<td>
				  <form action="{{action('CannedMessageController@destroy', $cannedmessage['id'])}}" method="post">
					<a href="{{action('CannedMessageController@edit', $cannedmessage['id'])}}" data-title="{{ _lang('Update Canned Message') }}" class="btn btn-warning btn-sm ajax-modal">{{ _lang('Edit') }}</a>
					<a href="{{action('CannedMessageController@show', $cannedmessage['id'])}}" data-title="{{ _lang('View Canned Message') }}" class="btn btn-info btn-sm ajax-modal">{{ _lang('View') }}</a>
					{{ csrf_field() }}
					<input name="_method" type="hidden" value="DELETE">
					<button class="btn btn-danger btn-sm btn-remove" type="submit">{{ _lang('Delete') }}</button>
				  </form>
				</td>
			  </tr>
			  @endforeach
			</tbody>
		  </table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/canned_message/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('View Canned Message') }}</div>

	<div class="panel-body">
	  <table class="table table-bordered">
		<tr><td>{{ _lang('Name') }}</td><td>{{ $cannedmessage->name }}</td></tr>
			<tr><td>{{ _lang('Message') }}</td><td>{{ $cannedmessage->message }}</td></tr>
			
	  </table>
	</div>
  </div>
 </div>
</div>
@endsection