routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => ['install']], function () {	

	Auth::routes();
	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

	Route::group(['middleware' => ['auth']], function () {
		
		Route::get('show_online_operator', 'DashboardController@show_online_operator');
		Route::get('dashboard', 'DashboardController@index');
		Route::get('widget_preview', 'DashboardController@widget_preview');
		Route::get('widget_code', 'DashboardController@widget_code');
        
		
		//User Controller
		Route::post('users/update_user_activity', 'UserController@update_user_activity');
		Route::resource('users','UserController');
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		
		Route::resource('departments','DepartmentController');
		Route::resource('canned_messages','CannedMessageController');
		
		//Message Controller
		Route::get('message/chat/{chat_request_id?}', 'MessageController@chat');
		Route::post('message/upload_file', 'MessageController@upload_file');
		Route::post('message/send_message', 'MessageController@send_message');
		Route::get('message/end_chat/{chat_request_id}', 'MessageController@end_chat');
		Route::get('message/get_messages/{chat_request_id}/{last_id?}', 'MessageController@get_messages');
		Route::get('message/get_chat_history_data', 'MessageController@get_chat_history_data');
		Route::get('message/chat_history/{id?}', 'MessageController@chat_history');
		Route::get('message/remove_history/{id}', 'MessageController@remove_history');	
		
		//Transfer Chat Window
		Route::get('chat/transfer_window', 'MessageController@chat_transfer_window');
		Route::get('chat/transfer_chat/{chat_request_id}/{operator_id}/{guest_id}', 'MessageController@transfer_chat');
			
		//Blacklist Controller
		Route::resource('blacklists','BlacklistController');
		
		//Offline Message
		Route::resource('offline_messages','OfflineMessageController');
		
		//Language Controller
		Route::resource('languages','LanguageController');	
		
		//Utility Controller
		Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
		Route::match(['get', 'post'],'administration/widget_settings/{store?}', 'UtilityController@widget_settings')->name('widget_settings.update');
		Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
		Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');
		Route::get('administration/toggle_offline_mode', 'UtilityController@toggle_offline_mode')->name('utility.toggle_offline_mode');
		
	});
	
});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

//Public Route
Route::get('chat_widget.js', 'GuestController@show_chat_widget');
Route::get('widget_content', 'GuestController@widget_content');
Route::post('guest/store_guest_user', 'GuestController@store_guest_user');
Route::post('guest/update_user_activity', 'GuestController@update_user_activity');
Route::post('guest/upload_file', 'GuestController@upload_file');
Route::post('guest/send_message', 'GuestController@send_message');
Route::post('guest/send_offline_message', 'GuestController@send_offline_message');
Route::get('guest/get_messages/{last_id?}', 'GuestController@get_messages');
Route::get('guest/end_chat', 'GuestController@end_chat');

app/Http/Controllers/LanguageController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class LanguageController extends Controller
{
	
	public function __construct()
    {
        $this->middleware('admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('backend.administration.language.list');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
       return view('backend.administration.language.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
		@ini_set('max_execution_time', 0);
		@set_time_limit(0);
		
        $this->validate($request, [
            'language_name' => 'required|alpha|string|max:30',
        ]);
		
		$name = $request->language_name;
		
		if(file_exists(resource_path() . "/language/$name.php")){
			return redirect()->back()->with('error',_lang('Language already exists !'));
		}
		
		$language = file_get_contents(resource_path() . "/language/language.php");
		$new_file = fopen(resource_path() . "/language/$name.php",'w+');
		fwrite($new_file,$language);
		fclose($new_file);
		
		return redirect('languages')->with('success',_lang('Language Created Sucessfully'));
    
	}

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if(file_exists(resource_path() . "/language/$id.php")){
			require (resource_path() . "/language/$id.php");
		    return view('backend.administration.language.edit',compact('language','id'));
		}
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {	
	    @ini_set('max_execution_time', 0);
		@set_time_limit(0);
		
		$contents="<?php \n\n";
		$contents.='$language=array();'."\n\n";	  
		foreach($_POST['language'] as $key => $value){
		  $contents.='$language["'.str_replace("_"," ",$key).'"]="'.$value.'";'."\n";
		}

		$file = fopen(resource_path() . "/language/$id.php","w");
		
		if(fwrite($file, $contents)){
		   return redirect('languages')->with('success',_lang('Updated Sucessfully'));
		}else{
		   return redirect('languages')->with('success',_lang('Update failed !'));
		}	
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if(file_exists(resource_path() . "/language/$id.php")){
			unlink(resource_path() . "/language/$id.php");
			return redirect('languages')->with('success',_lang('Removed Sucessfully'));
		}
    }
}

resources/views/backend/administration/language/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-6">
	<div class="panel panel-default">
	<div class="panel-heading title">{{ _lang('Add New Language') }}</div>

	<div class="panel-body">
	  <form method="post" class="validate" autocomplete="off" action="{{ url('languages') }}">
		{{ csrf_field() }}
		
		<div class="col-md-12">
		  <div class="form-group">
			<label class="control-label">{{ _lang('Language Name') }}</label>						
			<input type="text" class="form-control" name="language_name" value="{{ old('language_name') }}" required>
		  </div>
		</div>

		
		<div class="form-group">
		  <div class="col-md-12">
			<button type="submit" class="btn btn-primary">{{ _lang('Create Language') }}</button>
		  </div>
		</div>
	  </form>
	</div>
  </div>
 </div>
</div>
@endsection

resources/views/backend/administration/language/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading title">{{ _lang('Edit Translation') }}</div>

	<div class="panel-body">
	  <form method="post" class="validate" autocomplete="off" action="{{ action('LanguageController@update', $id) }}">
		{{ csrf_field() }}
		<input name="_method" type="hidden" value="PATCH">
		
		@foreach($language as $key=>$lang)
		<div class="col-md-6">
		  <div class="form-group">
			<label class="control-label">{{ ucwords($key) }}</label>						
			<input type="text" class="form-control" name="language[{{ str_replace(' ','_',$key) }}]" value="{{ $lang }}" required>
		  </div>
		</div>
        @endforeach
		
		<div class="form-group">
		  <div class="col-md-12">
			<button type="submit" class="btn btn-primary">{{ _lang('Save Translation') }}</button>
		  </div>
		</div>
	  </form>
	</div>
  </div>
 </div>
</div>
@endsection

resources/views/backend/administration/language/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-8">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ _lang('Languages') }}</span>
			<a class="btn btn-primary btn-sm pull-right" href="{{ route('languages.create') }}">{{ _lang('Add New') }}</a>
			</div>

			<div class="panel-body">
			 <table class="table table-bordered data-table">
				<thead>
				  <tr>
					<th>{{ _lang('Language Name') }}</th>
					<th>{{ _lang('Edit Translation') }}</th>
					<th>{{ _lang('Remove') }}</th>
				  </tr>
				</thead>
				<tbody>
				  
				  @foreach(get_language_list() as $language)
				  <tr>
					<td class='role_name'>{{ ucwords($language) }}</td>
					<td>
						<a href="{{ action('LanguageController@edit', $language) }}" class="btn btn-info btn-sm">{{ _lang('Edit Translation') }}</a>
					</td>	
					<td>
					    <form action="{{action('LanguageController@destroy', $language)}}" method="post">
						   {{ csrf_field() }}
						   <input name="_method" type="hidden" value="DELETE">
						   <button class="btn btn-danger btn-sm btn-remove" type="submit">{{ _lang('Delete') }}</button>
						</form>
					</td>
				  </tr>
				  @endforeach
				</tbody>
			  </table>
			</div>
		</div>
	</div>
</div>

@endsection