routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Route::group(['middleware' => ['install']], function () {	

	Auth::routes();
	Route::get('/logout', '\App\Http\Controllers\Auth\LoginController@logout');

	Route::group(['middleware' => ['auth']], function () {
		
		Route::get('show_online_operator', 'DashboardController@show_online_operator');
		Route::get('dashboard', 'DashboardController@index');
		Route::get('widget_preview', 'DashboardController@widget_preview');
		Route::get('widget_code', 'DashboardController@widget_code');
        
		
		//User Controller
		Route::post('users/update_user_activity', 'UserController@update_user_activity');
		Route::resource('users','UserController');
		
		//Profile Controller
		Route::get('profile/my_profile', 'ProfileController@my_profile');
		Route::get('profile/edit', 'ProfileController@edit');
		Route::post('profile/update', 'ProfileController@update');
		Route::get('profile/change_password', 'ProfileController@change_password');
		Route::post('profile/update_password', 'ProfileController@update_password');
		
		Route::resource('departments','DepartmentController');
		Route::resource('canned_messages','CannedMessageController');
		
		//Message Controller
		Route::get('message/chat/{chat_request_id?}', 'MessageController@chat');
		Route::post('message/upload_file', 'MessageController@upload_file');
		Route::post('message/send_message', 'MessageController@send_message');
		Route::get('message/end_chat/{chat_request_id}', 'MessageController@end_chat');
		Route::get('message/get_messages/{chat_request_id}/{last_id?}', 'MessageController@get_messages');
		Route::get('message/get_chat_history_data', 'MessageController@get_chat_history_data');
		Route::get('message/chat_history/{id?}', 'MessageController@chat_history');
		Route::get('message/remove_history/{id}', 'MessageController@remove_history');	
		
		//Transfer Chat Window
		Route::get('chat/transfer_window', 'MessageController@chat_transfer_window');
		Route::get('chat/transfer_chat/{chat_request_id}/{operator_id}/{guest_id}', 'MessageController@transfer_chat');
			
		//Blacklist Controller
		Route::resource('blacklists','BlacklistController');
		
		//Offline Message
		Route::resource('offline_messages','OfflineMessageController');
		
		//Language Controller
		Route::resource('languages','LanguageController');	
		
		//Utility Controller
		Route::match(['get', 'post'],'administration/general_settings/{store?}', 'UtilityController@settings')->name('general_settings.update');
		Route::match(['get', 'post'],'administration/widget_settings/{store?}', 'UtilityController@widget_settings')->name('widget_settings.update');
		Route::post('administration/upload_logo', 'UtilityController@upload_logo')->name('general_settings.update');
		Route::get('administration/backup_database', 'UtilityController@backup_database')->name('utility.backup_database');
		Route::get('administration/toggle_offline_mode', 'UtilityController@toggle_offline_mode')->name('utility.toggle_offline_mode');
		
	});
	
});

Route::get('/installation', 'Install\InstallController@index');
Route::get('install/database', 'Install\InstallController@database');
Route::post('install/process_install', 'Install\InstallController@process_install');
Route::get('install/create_user', 'Install\InstallController@create_user');
Route::post('install/store_user', 'Install\InstallController@store_user');
Route::get('install/system_settings', 'Install\InstallController@system_settings');
Route::post('install/finish', 'Install\InstallController@final_touch');

//Public Route
Route::get('chat_widget.js', 'GuestController@show_chat_widget');
Route::get('widget_content', 'GuestController@widget_content');
Route::post('guest/store_guest_user', 'GuestController@store_guest_user');
Route::post('guest/update_user_activity', 'GuestController@update_user_activity');
Route::post('guest/upload_file', 'GuestController@upload_file');
Route::post('guest/send_message', 'GuestController@send_message');
Route::post('guest/send_offline_message', 'GuestController@send_offline_message');
Route::get('guest/get_messages/{last_id?}', 'GuestController@get_messages');
Route::get('guest/end_chat', 'GuestController@end_chat');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'user_type',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
	
	public function department()
    {
		return $this->belongsTo('App\Department')->withDefault();
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use App\User;
use Validator;
use Auth;
use Hash;

class UserController extends Controller
{

    public function __construct()
    {
        $this->middleware('admin')->except('update_user_activity');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all()->sortByDesc("id");
        return view('backend.user.list',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
		if( ! $request->ajax()){
		   return view('backend.user.create');
		}else{
           return view('backend.user.modal.create');
		}
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {	
		$validator = Validator::make($request->all(), [
			'name' => 'required|max:191',
			'email' => 'required|email|unique:users|max:191',
			'password' => 'required|max:20|min:6|confirmed',
			'user_type' => 'required',
			'department_id' => 'required_if:user_type,operator',
			'profile_picture' => 'nullable|image|max:5120',
		]);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect('users/create')
							->withErrors($validator)
							->withInput();
			}			
		}
			
        $user= new User();
	    $user->name = $request->input('name');
		$user->email = $request->input('email');
		$user->password = Hash::make($request->password);
		$user->user_type = $request->input('user_type');
		$user->department_id = $request->input('department_id');
	    if ($request->hasFile('profile_picture')){
           $image = $request->file('profile_picture');
           $file_name = "profile_".time().'.'.$image->getClientOriginalExtension();
           $image->move(base_path('public/uploads/profile/'),$file_name);
           $user->profile_picture = $file_name;
		}
        $user->save();
        
		if(! $request->ajax()){
           return redirect('users/create')->with('success', _lang('Information has been added sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'store','message'=>_lang('Information has been added sucessfully'),'data'=>$user]);
		}
        
   }
	

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request,$id)
    {
        $user = User::find($id);
		if(! $request->ajax()){
		    return view('backend.user.view',compact('user','id'));
		}else{
			return view('backend.user.modal.view',compact('user','id'));
		} 
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request,$id)
    {
        $user = User::find($id);
		if(! $request->ajax()){
		   return view('backend.user.edit',compact('user','id'));
		}else{
           return view('backend.user.modal.edit',compact('user','id'));
		}  
        
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		$messages = [
			'department_id.required_if' => 'Operator needs to assign a department !',
		];
		$validator = Validator::make($request->all(), [
			'name' => 'required|max:191',
			'email' => [
                'required',
                Rule::unique('users')->ignore($id),
            ],
			'password' => 'nullable|max:20|min:6|confirmed',
			'user_type' => 'required',
			'department_id' => 'required_if:user_type,operator',
			'profile_picture' => 'nullable|image|max:5120',
		],$messages);
		
		if ($validator->fails()) {
			if($request->ajax()){ 
			    return response()->json(['result'=>'error','message'=>$validator->errors()->all()]);
			}else{
				return redirect()->route('users.edit', $id)
							->withErrors($validator)
							->withInput();
			}			
		}
	
        $user = User::find($id);
		$user->name = $request->input('name');
		$user->email = $request->input('email');
		if($request->password){
            $user->password = Hash::make($request->password);
        }
		$user->user_type = $request->input('user_type');
	    $user->department_id = $request->input('department_id');
		if ($request->hasFile('profile_picture')){
           $image = $request->file('profile_picture');
           $file_name = "profile_".time().'.'.$image->getClientOriginalExtension();
           $image->move(base_path('public/uploads/profile/'),$file_name);
           $user->profile_picture = $file_name;
		}
        $user->save();
		
		if(! $request->ajax()){
           return redirect('users')->with('success', _lang('Information has been updated sucessfully'));
        }else{
		   return response()->json(['result'=>'success','action'=>'update', 'message'=>_lang('Information has been updated sucessfully'),'data'=>$user]);
		}
	    
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect('users')->with('success',_lang('Information has been deleted sucessfully'));
    }
	
	public function update_user_activity(Request $request){
		date_default_timezone_set(get_option('timezone'));
		$count_transfer_user = 0;
		
		$user = \App\User::find(Auth::User()->id);
		$user->last_activity = date("Y-m-d H:i:s");
		$user->save();
		
		//GET Operator Current Chat Request ID
		$chat_request_id = $request->session()->get('operator_chat_request_id');
		
		$online_users = array();
		$new_users = array();
		
		//Show Online Operator
		$online_users['operator'] = "";
		$online_users['guest'] = "";
		$online_users['transfer_guest'] = "";
		foreach(online_operator() as $user){
			$online_users['operator'] .='<li class="active_operator"><a data-id="'.$user->id.'" data-email="'.$user->email.'" href="#">'.$user->name.'</a></li>';  
		}
		
		foreach(online_guest() as $guest){
			if($guest->id == NULL){
			   continue;
			}
			$operator ="";
			if($guest->operator !=""){
				$online_users['guest'] .='<li class="active_visitor"><a href="'.url('message/chat/'.$guest->chat_request_id).'" data-id="'.$guest->id.'" data-url="'.$guest->url.'" data-ip="'.$guest->ip.'" data-requestid="'.$guest->chat_request_id.'" data-name="'.$guest->name.'" data-operator="'.$guest->operator.'" data-email="'.$guest->email.'" data-mobile="'.$guest->mobile.'">'.$guest->name.' <span class="message_count">'.$guest->unread_message.'</span></a></li>';
			}else{
				array_push($new_users,array('id'=>$guest->id, 'name'=>$guest->name)); 
				$online_users['guest'] .='<li class="active_visitor guest_visitor"><a href="'.url('message/chat/'.$guest->chat_request_id).'" data-id="'.$guest->id.'" data-url="'.$guest->url.'" data-ip="'.$guest->ip.'" data-requestid="'.$guest->chat_request_id.'" data-name="'.$guest->name.'" data-operator="'.$guest->operator.'" data-email="'.$guest->email.'" data-mobile="'.$guest->mobile.'">'.$guest->name.' <span class="message_count">'.$guest->unread_message.'</span></a></li>';
		    }
			
			
			if($guest->chat_status == "chat_transfer" && $guest->operator_id == Auth::User()->id){
				$online_users['transfer_guest'] .='<li class="active_visitor transfer_visitor"><a href="'.url('message/chat/'.$guest->chat_request_id).'" data-id="'.$guest->id.'" data-url="'.$guest->url.'" data-ip="'.$guest->ip.'" data-requestid="'.$guest->chat_request_id.'" data-name="'.$guest->name.'" data-operator="'.$guest->operator.'" data-email="'.$guest->email.'" data-mobile="'.$guest->mobile.'">'.$guest->name.' <span class="message_count">'.$guest->unread_message.'</span></a></li>';
			    $count_transfer_user++;
			}
		}
		
		$chat_request = [];
		if($chat_request_id !=""){
			$chat_request = \App\ChatRequest::find($chat_request_id);
			$chat_request->operator_is_typing = $request->typing;
			$chat_request->save();
		}
		
		echo json_encode(
			array("online_users"=>$online_users,
			"chat_request"=>$chat_request,
			"new_users"=> $new_users,
			"count_transfer_user"=>$count_transfer_user)
		  );
	}
}

resources/views/backend/user/create.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('Add User') }}</div>

	<div class="panel-body">
		<form method="post" class="validate" autocomplete="off" action="{{url('users')}}" enctype="multipart/form-data">
		    <div class="col-md-6">
				{{ csrf_field() }}
				
				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Name') }}</label>						
					<input type="text" class="form-control" name="name" value="{{ old('name') }}" required>
				  </div>
				</div>

				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Email') }}</label>						
					<input type="email" class="form-control" name="email" value="{{ old('email') }}" required>
				  </div>
				</div>

				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Password') }}</label>						
					<input type="password" class="form-control" name="password" value="{{ old('password') }}" required>
				  </div>
				</div>
				
				<div class="col-md-12">
				 <div class="form-group">
					<label class="control-label">{{ _lang('Confirm Password') }}</label>						
					<input type="password" class="form-control" name="password_confirmation" required>
				 </div>
				</div>

				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('User Type') }}</label>						
					<select class="form-control" id="user-type" name="user_type" required>
					  <option value="operator">{{ _lang('Operator') }}</option>
					  <option value="admin">{{ _lang('Admin') }}</option>
					</select>
				  </div>
				</div>
				
				<div class="col-md-12">
				  <div class="form-group">
					<label class="control-label">{{ _lang('Department') }}</label>						
					<select class="form-control select2" id="department_id" name="department_id">
					  <option value="">{{ _lang('Select One') }}</option>
					  {{ create_option("departments","id","department") }}
					</select>
				  </div>
				</div>
				
				<div class="form-group">
				  <div class="col-md-12">
					<button type="reset" class="btn btn-danger">{{ _lang('Reset') }}</button>
					<button type="submit" class="btn btn-primary">{{ _lang('Save') }}</button>
				  </div>
				</div>
				
			</div>
			
			<div class="col-md-6">		
				<div class="col-md-12">
				 <div class="form-group">
					<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
					<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="">
				 </div>
				</div>
			</div>	
		  </form>
	  
	</div>
  </div>
 </div>
</div>
@endsection

@section('js-script')
<script>
$("#user_type").val("{{ old('user_type') }}");
</script>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default">
			<div class="panel-heading">{{ _lang('Update User') }}</div>

			<div class="panel-body">
			<form method="post" class="validate" autocomplete="off" action="{{action('UserController@update', $id)}}" enctype="multipart/form-data">
				<div class="col-md-6">
					{{ csrf_field()}}
					<input name="_method" type="hidden" value="PATCH">				
					
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Name') }}</label>						
						<input type="text" class="form-control" name="name" value="{{ $user->name }}" required>
					 </div>
					</div>

					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Email') }}</label>						
						<input type="email" class="form-control" name="email" value="{{ $user->email }}" required>
					 </div>
					</div>

					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Password') }}</label>						
						<input type="password" class="form-control" name="password" value="">
					 </div>
					</div>
					
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Confirm Password') }}</label>						
						<input type="password" class="form-control" name="password_confirmation" value="">
					 </div>
					</div>

					<div class="col-md-12">
					  <div class="form-group">
						<label class="control-label">{{ _lang('User Type') }}</label>						
						<select class="form-control" name="user_type" id="user_type" required>
						  <option value="operator">{{ _lang('Operator') }}</option>
						  <option value="admin">{{ _lang('Admin') }}</option>
						</select>
					  </div>
					</div>
					
					<div class="col-md-12">
					  <div class="form-group">
						<label class="control-label">{{ _lang('Department') }}</label>						
						<select class="form-control select2" id="department_id" name="department_id">
						  <option value="">{{ _lang('Select One') }}</option>
						  {{ create_option("departments","id","department",$user->department_id) }}
						</select>
					  </div>
					</div>
					
					<div class="form-group">
					  <div class="col-md-12">
						<button type="submit" class="btn btn-primary">{{ _lang('Update') }}</button>
					  </div>
					</div>
				</div>
				
				<div class="col-md-6">
					<div class="col-md-12">
					 <div class="form-group">
						<label class="control-label">{{ _lang('Profile Picture') }} ( 300 X 300 {{ _lang('for better view') }} )</label>						
						<input type="file" class="dropify" name="profile_picture" data-allowed-file-extensions="png jpg jpeg PNG JPG JPEG" data-default-file="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : '' }}" >
					 </div>
					</div>
                </div>

			</form>
			</div>
		</div>
	</div>
</div>

@endsection

@section('js-script')
<script>
$("#user_type").val("{{ $user->user_type }}");
</script>
@endsection

resources/views/backend/user/list.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
	<div class="col-md-12">
		<div class="panel panel-default no-export">
			<div class="panel-heading"><span class="panel-title">{{ _lang('User List') }}</span>
			<a class="btn btn-primary btn-sm pull-right ajax-modal" data-title="{{ _lang('Add User') }}" href="{{route('users.create')}}">{{ _lang('Add New') }}</a>
			</div>

			<div class="panel-body">
			 @if (\Session::has('success'))
			  <div class="alert alert-success">
				<p>{{ \Session::get('success') }}</p>
			  </div>
			  <br />
			 @endif
			<table class="table table-bordered data-table">
			<thead>
			  <tr>
				<th>{{ _lang('Name') }}</th>
				<th>{{ _lang('Email') }}</th>
				<th>{{ _lang('User Type') }}</th>
				<th>{{ _lang('Department') }}</th>
				<th>{{ _lang('Action') }}</th>
			  </tr>
			</thead>
			<tbody>
			  
			  @foreach($users as $user)
			    <tr id="row_{{ $user->id }}">
					<td class='name'>{{ $user->name }}</td>
					<td class='email'>{{ $user->email }}</td>
					<td class='user_type'>{{ ucwords($user->user_type) }}</td>					
					<td class='user_type'>{{ $user->department->department }}</td>					
					<td>
					  <form action="{{action('UserController@destroy', $user['id'])}}" method="post">
						<a href="{{action('UserController@edit', $user['id'])}}" data-title="{{ _lang('Update User') }}" class="btn btn-warning btn-sm ajax-modal">{{ _lang('Edit') }}</a>
						<a href="{{action('UserController@show', $user['id'])}}" data-title="{{ _lang('View User') }}" class="btn btn-info btn-sm ajax-modal">{{ _lang('View') }}</a>
						{{ csrf_field() }}
						<input name="_method" type="hidden" value="DELETE">
						<button class="btn btn-danger btn-sm btn-remove" type="submit">{{ _lang('Delete') }}</button>
					  </form>
					</td>
			    </tr>
			  @endforeach
			</tbody>
		  </table>
			</div>
		</div>
	</div>
</div>

@endsection

resources/views/backend/user/view.blade.php
@extends('layouts.app')

@section('content')
<div class="row">
	<div class="col-md-12">
	<div class="panel panel-default">
	<div class="panel-heading">{{ _lang('View User') }}</div>

	<div class="panel-body">
	  <table class="table table-bordered">
		<tr><td colspan="2"><img style="margin: auto;" class="thumb-image-md thumbnail" src="{{ $user->profile_picture != "" ? asset('public/uploads/profile/'.$user->profile_picture) : '' }}"></td></tr>
		<tr><td>{{ _lang('Name') }}</td><td>{{ $user->name }}</td></tr>
		<tr><td>{{ _lang('Email') }}</td><td>{{ $user->email }}</td></tr>
		<tr><td>{{ _lang('User Type') }}</td><td>{{ $user->user_type }}</td></tr>	
	  </table>
	</div>
  </div>
 </div>
</div>
@endsection